# Generated by Django 3.1.14 on 2022-06-12 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_auto_20220612_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='evolves_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon'),
        ),
    ]
