# Generated by Django 3.1.14 on 2022-06-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_pokemon_evolves_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='evolves_to',
            new_name='evolves_from',
        ),
    ]
